services:

  postgres:
    image: postgres:18-alpine
    container_name: emailgen-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: emailgen
    volumes:
    - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # redis:
  #   image: redis:7-alpine
  #   container_name: emailgen-redis
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   command: redis-server --appendonly yes
  #   healthcheck:
  #     test: ["CMD", "redis-cli", "ping"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  #   restart: unless-stopped

  migrate:
    container_name: ephemeral-migrate
    build:
      context: .
      dockerfile: ./Dockerfile.migration
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ./.env
    volumes:
      - ./src/database/drizzle:/app/src/database/drizzle
    restart: "no"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: emailgen-api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    env_file:
      - ./.env
    depends_on:
      postgres:
        condition: service_healthy
      # redis:
      #   condition: service_healthy
      ollama:
        condition: service_started
    restart: unless-stopped

  frontend:
    build:
      context: ../../frontend
      dockerfile: Dockerfile
    container_name: emailgen-frontend
    ports:
      - "80:80"
    env_file:
      - ../../frontend/.env
    #depends_on:
    #  api:
    #    condition: service_healthy
    restart: unless-stopped

  ollama:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
    volumes:
        - ollama:/root/.ollama
    ports:
        - 11434:11434
    container_name: ollama
    image: ollama/ollama

volumes:
  postgres_data:
  # redis_data:
  ollama:
      external: true
      name: ollama
